name: Assets update

on:
  workflow_call:      # make it callable from other workflows
  workflow_dispatch:  # allow manual triggering from GitHub UI
  
jobs:
  update-files:
    permissions:
      contents: write # See https://stackoverflow.com/questions/72851548/permission-denied-to-github-actionsbot
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Python script to generate charts
        run: python pizza_report.py
      - name: Run Python script to generate HTML heatmap
        run: python heatmap.py
        
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/charts/*.png
          git add docs/*.html
          git commit -m "Auto-update charts and HTML on data change" || echo "No changes to commit"
          git push
