name: Append CSV to Excel

on:
  workflow_call:      # make it callable from other workflows
  workflow_dispatch:  # allow manual triggering from GitHub UI

jobs:
  append-to-excel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pandas openpyxl

      - name: Append CSV rows to Excel
        run: |
          python scripts/format_data.py
      - name: Cleanup CSV
        run: |
          echo "Date, Pizza, #, Pizzeria" > git data/input/upload.csv 

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]@users.noreply.github.com"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/data.xlsx input/data/upload.csv
          git commit -m "Append data from CSV" || echo "Ngit o changes to commit"
          git pull --rebase origin ${{ github.ref_name }}
          git push
